name: Linters

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install black codespell types-docutils mypy

    - name: Check with black
      run: black --check src/pinnwand

    # - name: Check with mypy
    #   run: mypy src/pinnwand
