name: Vulnerability Scanners

on:
  workflow_call:

jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bandit pip-audit

    - name: Check with bandit
      run: bandit -r src/pinnwand

    - name: Check with pip-audit
      run: pip-audit --requirement requirements.txt
